#controllers:
#    resource: ../../src/Infrastructure/Controller/Web/
#    type: annotation

rest_controller:
    resource: ../../src/Infrastructure/Controller/Api/
    type: annotation
    prefix: /api
